steps:
# Install dependencies and build the frontend
- name: 'node:14'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd notflix/frontend
    npm install
    npm run build --prod
    cp -r dist/notflix /workspace/frontend

# Install dependencies and build the backend
- name: 'node:14'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd notflix/backend
    npm install
    npm run build
    cp -r dist /workspace/backend

# Build Docker images
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/notflix-frontend', '-f', 'notflix/frontend/Dockerfile', 'notflix/frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/notflix-backend', '-f', 'notflix/backend/Dockerfile', 'notflix/backend']

# Push Docker images to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/notflix-frontend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/notflix-backend']

# Deploy to Kubernetes
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'k8s/frontend-deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'k8s/backend-deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
