apiVersion: apps/v1
kind: Deployment
metadata:
  name: notflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notflix-frontend
  template:
    metadata:
      labels:
        app: notflix-frontend
    spec:
      containers:
      - name: notflix-frontend
        image: gcr.io/teak-instrument-429819-b8/notflix-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notflix-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: notflix-frontend
