name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: teak-instrument-429819-b8
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker images
      run: |
        cd notflix/frontend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/notflix-frontend .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/notflix-frontend
        cd ../backend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/notflix-backend .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/notflix-backend

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/backend-deployment.yaml
